LauraConcepcion/consulLPA

- app/views/custom/welcome/index.html.erb
Signed-off-by: Laura Concepción <lconcepcion@usabi.es>
References
===================
> Add references to related Issues/Pull Requests/Travis Builds/Rollbar errors/etc...
Objectives
===================
> What are the objectives of this changes? (If there is no related Issue with an explanation)
Visual Changes
===================
Notes
===================
> Change banner to insert new canteras process

- app/models/custom/budget.rb
- app/views/custom/welcome/index.html.erb
Also fixes an error when saving budgets (missing reference)
> Update homepage videos

- app/models/ability.rb
- app/views/proposals/index.html.erb
References
===================
> Add references to related Issues/Pull Requests/Travis Builds/Rollbar errors/etc...
Objectives
===================
> What are the objectives of this changes? (If there is no related Issue with an explanation)
Visual Changes
===================
Notes
===================
> hide proposal button

- config/deploy.rb
> Updates deploy settings

- app/assets/stylesheets/custom.scss
- app/controllers/custom/budgets/groups_controller.rb
- app/controllers/custom/budgets/investments_controller.rb
- app/controllers/custom/budgets_controller.rb
- app/views/custom/budgets/index.html.erb
- app/views/custom/budgets/results/show.html.erb
- app/views/custom/budgets/show.html.erb
- config/locales/custom/es/budgets.yml
Signed-off-by: Laura Concepción <lconcepcion@usabi.es>
> Added new investment status lists

- lib/custom/wysiwyg_sanitizer.rb
Signed-off-by: Laura Concepción <lconcepcion@usabi.es>
> Forgotten file lib/custom/wysiwyg_sanitizer

- app/assets/stylesheets/custom.scss
Signed-off-by: Laura Concepción <lconcepcion@usabi.es>
> show all pagination li rendered

- app/models/comment.rb
- app/models/poll/question.rb
- app/views/custom/polls/questions/_answers.html.erb
> Corrijo los comentarios de las preguntas de una consulta

- Gemfile
- Gemfile.lock
- app/views/custom/budgets/investments/_header.html.erb
> Fix error of progressbar attributes

- app/views/custom/welcome/index.html.erb
> Add bullets to slider

- config/locales/custom/es/budgets.yml
> Change some text

- app/controllers/admin/stats_controller.rb
- app/controllers/custom/admin/stats_controller.rb
> Fix heading duplication in statistic view

- app/components/budgets/subheader_component.html.erb
- app/models/abilities/common.rb
Allow level users to create proposals but not participate in voting.
> User level_one could create budgets investment

- config/application_custom.rb
> Change time zone to Atlantic/Canary

- lib/custom/sms_api.rb
> Fix uri sms

- app/assets/javascripts/custom/investment_report_alert.js
- app/assets/javascripts/custom/valuation_budget_investment_form.js
- app/assets/javascripts/valuation_budget_investment_form.js
- app/controllers/custom/valuation/budget_investments_controller.rb
- app/views/custom/valuation/budget_investments/_dossier.html.erb
- app/views/custom/valuation/budget_investments/_dossier_form.html.erb
- app/views/custom/valuation/budget_investments/_feasibility_explanation.html.erb
- config/locales/custom/es/valuation.yml
- db/migrate/20230712125640_add_new_explanation_fields_to_investments.rb
- db/schema.rb
> feat: Allow to add report for all investment valuation decisions

- app/views/custom/valuation/budget_investments/_dossier.html.erb
> fix: Template wrong relative path

- app/controllers/custom/admin/system_emails_controller.rb
- config/locales/custom/es/admin.yml
> feat: Add feasible investment email to admin previews list

- Gemfile.lock
- Gemfile_custom
- app/controllers/custom/management/document_verifications_controller.rb
- app/models/custom/budget.rb
- app/models/custom/user.rb
- app/models/custom/verification/management/document.rb
- app/views/custom/management/_user_permissions.html.erb
- app/views/custom/management/document_verifications/verified.html.erb
- config/locales/custom/es/general.yml
- config/schedule.rb
- config/secrets.yml.example
- lib/custom/slack_notifier.rb
I verify residency in user management and automatic change of budget phase
> Add verification of residence in user management and automatic change of budget phase

- app/controllers/custom/management/document_verifications_controller.rb
> fix: Fix name of method

- app/controllers/custom/management/document_verifications_controller.rb
- app/models/custom/user.rb
- app/models/custom/verification/management/document.rb
- config/locales/es/management.yml
> fix: Verfication new user

- app/models/custom/user.rb
> feat: Temporarily remove 12-month check for residence verification

- app/models/custom/user.rb
> feat: Only user level two and level three

- app/controllers/welcome_controller.rb
> feat: Only list investment with milestone
